apiVersion: v1
kind: Service
metadata:
  name: web-np
  labels:
    courselabs.co: project-cicd
    app: widgetario
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:  
    app: widgetario
    component: web
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: web-np
  labels:
    courselabs.co: project-cicd
    app: widgetario
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30008
  selector:  
    app: widgetario
    component: web
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    courselabs.co: project-cicd
    app: widgetario
spec:
  replicas: 2
  selector:
    matchLabels:
        app: widgetario
        component: web
  template:
    metadata:
      labels: 
        app: widgetario
        component: web
    spec:
      containers:
        - name: app
          image: widgetario/web:21.12
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http